# http://travis-ci.org/spectralDNS/shenfun

language: generic

os: osx
osx_image: xcode7.3

sudo: False

env:
  matrix:
    - CONDA_PY=27
    - CONDA_PY=36

  global:
    # "travis encrypt BINSTAR_TOKEN=<token> --repo spectralDNS/shenfun"
    - secure: "F6Ne6vs/z74+EPKdwvA9owHy2HH+tdkTgxpIUMzthGqHUC9bNHW54sZkWf+Vy8xNvdBEZ1c+A3REHFxpv+8tXyWP36SPPn6kKuTHuJLCGs4+vRIZGwJQ90Fxvfg2rLZ/iGd+CJGhwPyvSrUdJ2KtaRKQMjoIdUNXkQU78+TGMKsAuWdj8AGWbsQOhCcUCAR7EaNyKVtezW+tm9rX0dssQsJhgZL8vKYBbVwZuagapgAA7v8eCAs52ZsELNDz0qf6KVmNNZZfC7p+MbTbiedu9KpniE5vGnha/uS8TWoVkt3j00yMwcb01TYD1A88dSVSPflm1iRo6GqLtLiwyqti4zQPyGV6NRTOrJFUl4JcByf6SMTRyp297CUYND7IidovESwg/AhVZpGlcd2U6EFm87YIqBRCQch50KAIuhZ09Y1aggpJ0PzItytCxEoBAHrL9k25MXgzYs9L23V74fkyuUzWz6INPldDmXl+4yTRAO90PHhhH/ixD2UtXZqK3VVUbRBz0nRInzwZvBAKqgfHWXdkRP+ISZImNBogzeBDqhGS82VDx6l0q+GBgkSEW9Lfg8iSrcEwOiGyRhlDDmzV/F5ol+04do/IwsLGMYm1yP5xIy7T5wzs2Ywmv3ychkpS/7U+lKw9vc3UG/X+Xu80MTOQ0BCVdmcFucR5UFViM+I="

before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b
      source /Users/travis/miniconda3/bin/activate root
      conda config --set show_channel_urls true
      conda config --add channels conda-forge
      conda config --add channels spectralDNS
      pip install codecov pytest-cov python-coveralls
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
    - conda build conf/conda

after_success:
    - upload_or_check_non_existence ./conf/conda spectralDNS --channel main || exit 1
    - codecov
    - coveralls
