package:
  name: shenfun
  version: "1.0.1"

source:
  git_url: ../../

build:
  number: 2
  #script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy
    - scipy
    - cython
    - pyfftw
    - mpi4py
    - six
    - sympy

test:
  source_files:
    - tests

  imports:
    - mpi4py_fft
    - shenfun

  requires:
    - pytest
