package:
  name: shenfun
  version: "1.0"

source:
  git_url: ../../

build:
  number: 0
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy
    - scipy
    - mpiFFT4py
    - cython
    - pyfftw

test:
  source_files:
    - tests

  requires:
    - pytest
